### ISSUE TITLE
Request for sre_yield.oneString method

### ISSUE THREAD

**Issue by faraazc** [google/sre_yield#10]
For big regex I am seeing below error. Probably it is because too many combinations are generated. I would need just one of the string.

Probably sre_yield.oneString needs to be developed.

list(sre_yield.AllStrings(r'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot fit 'int' into an index-sized integer

**Comment by thatch** [comment]
If you'd like to get an arbitrary match, you can avoid listifying:

```py
x = sre_yield.AllStrings(...)
i = random.randint(0, x.__len__() - 1)
print(x[i])
```

However your list has a _lot_ of matches (59k decimal digits) and I'm not sure if you need a biased match of a certain length...

This also hits a bug that should be fixed by https://github.com/google/sre_yield/pull/11

**Comment by thatch** [comment]
#11 is now merged, I think you're good to go.
