### ISSUE TITLE
[feature request] Provide an iterateable object

### ISSUE THREAD

**Issue by cstayyab** [google/sre_yield#12]
To prevent memory overflow errors please provide an iterateable object so each string can be process separately.

**Example**:
Consider the following code:
```python
import sre_yield
matches = list(sre_yield.AllStrings("[a-z]{1,20}"))
```
The above generates `OverflowError` but if an iterateable object is provided then we can prevent this error. The expected outcome would be as follows:
 ```python
import sre_yield
for combination in sre_yeild.getIteratableCombinations("[a-z]{1,20}"):
    print(combination)
```

In this way we won't be needing memory for storing huge lists.

**Comment by thatch** [comment]
AllStrings supports `__iter__`, so this should work out of the box -- this is actually what list()` uses to get the values.  Here's an example:

```pycon
>>> import sre_yield
>>> it = iter(sre_yield.AllStrings("[a-z]{1,20}"))
>>> next(it)
'a'
>>> next(it)
'b'

```
