### ISSUE TITLE
slice len() raises TypeError even for small values

### ISSUE THREAD

**Issue by jayvdb** [google/sre_yield#16]
`len(sre_yield.AllMatches('\d+'))` raises `OverflowError: cannot fit 'int' into an index-sized integer`

`len(sre_yield.AllMatches('\d+', max_count=19))` raises `OverflowError: cannot fit 'int' into an index-sized integer`, but lower `max_count` is ok.

But using slices it gets interesting.

`len(sre_yield.AllMatches('\d+')[:16])` raises `TypeError: 'float' object cannot be interpreted as an integer` - same result for using `AllStrings` (`[:15]` is ok).  In this case, using `list` is a workaround - `len(list(sre_yield.AllStrings('\d+')[:16]))` = 16.

`len(sre_yield.AllMatches('\d+', max_count=1)[:16])` is ok, but `len(sre_yield.AllMatches('\d+', max_count=2)[:16])` and higher is not.

Looking at the code, I see a note about using `.__len__()` instead, and the solution for most cases becomes obvious.

**Comment by thatch** [comment]
The float part is coming from the division near the "Integer round up" comment.  I think that needs to be a floordiv.
