### ISSUE TITLE
upload a new version up to pypi?

### ISSUE THREAD

**Issue by ckot** [google/sre_yield#8]
version 1.0 (published 2014/02/14) up on pypi doesn't work with python3.  

It appears that the code here in 'master' has been updated to do so, although I haven't tried running/testing it in both py2 and 3.

If it does work for both, could someone upload a new version up to pypi?

**Comment by svelleweetakealot** [comment]
+1

**Comment by thatch** [comment]
I'll take this, I don't think @arp11 has had time.

**Comment by thatch** [comment]
Version 1.1 is up at https://pypi.org/project/sre_yield/#history -- can you verify this satisfies your need?

**Comment by arp11** [comment]
Thank you Tim!
